version: "3"

services:
  
    jenkins:
        image: jenkins/jenkins:2.249.2-lts-jdk11
        expose: 
            - 8080
        ports: 
            - "8080:8080"
        volumes:
            - ./volumes/jenkins:/var/jenkins_home