version: "3"

services:
    sonarqube:
        image: sonarqube:lts
        expose:
            - 9000
        ports:
            - "9000:9000"
        volumes:
            - ./volumes/sonarqube/conf:/opt/sonarqube/conf
            - ./volumes/sonarqube/data:/opt/sonarqube/data
            - ./volumes/sonarqube/logs:/opt/sonarqube/logs
            - ./volumes/sonarqube/extensions:/opt/sonarqube/extensions